config.code=2323
config.username=jonas
config.message=hola que tal como estas rubén!
config.listOfValue=hola,que,tal,el,dia,de,hoy
config.valuesMap={product: 'CPU Intel Core i7 12th', description: 'Alder Lake, 12 core, a 5 hz', price: '450'}